# exemplo deu um netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

# Redirecionamento de todas as rotas para /index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200